- name: Build and start the Docker containers
  command: docker-compose up --build -d
  args:
    chdir: /opt/laravel

- name: Wait for the application container to be ready
  wait_for:
    host: "127.0.0.1"
    port: 8000
    delay: 10
    timeout: 60

- name: Check if /var/www/lms exists inside the container
  shell: docker exec laravel_app test -d /var/www/lms
  register: lms_dir_check
  ignore_errors: true

- name: Clone LMS repository in the container if /var/www/lms does not exist
  command: docker exec laravel_app git clone https://github.com/abdelrahim3AA/Learning-Management-Systems-LMS_GP.git /var/www/lms
  when: lms_dir_check.rc != 0

- name: Run composer install in the container
  command: docker exec -w /var/www/lms laravel_app composer install
  
- name: Copy .env.example to .env in the container
  command: docker exec -w /var/www/lms laravel_app cp .env.example .env

- name: Generte Laravel aplication key
  command: docker exec -w /var/www/lms laravel_app php artisan key:generate
