---
- name: Set up Laravel application and MySQL
  hosts: localhost
  become: yes 
  vars:
    app_repo: "https://github.com/abdelrahim3AA/Learning-Management-Systems-LMS_GP"

  tasks:
    - name: Install system dependencies
      apt:
        name:
          - curl
          - composer
          - npm
          - git
          - php
          - php-xml
          - php-sqlite3
        state: present
        update_cache: yes 

    - name: Clone the LMS GitHub repository
      git:
        repo: "{{ app_repo }}"
        dest: /var/www/lms

    - name: Install NPM dependencies
      become: true 
      command: npm install
      args:
        chdir: /var/www/lms

    - name: Install Composer dependencies
      become: true 
      command: composer install
      args:
        chdir: /var/www/lms

    - name: Copy .env.example to .env
      copy:
        src: /var/www/lms/.env.example
        dest: /var/www/lms/.env

    - name: Uncomment the DB settings in .env
      replace:
        path: /var/www/lms/.env
        regexp: "#(DB_HOST|DB_PORT|DB_DATABASE|DB_USERNAME|DB_PASSWORD)"
        replace: '\1'

    - name: Generate Laravel application key
      command: php artisan key:generate
      args:
        chdir: /var/www/lms

    - name: Run Laravel migrations
      command: php artisan migrate
      args:
        chdir: /var/www/lms

    - name: Start Laravel development server
      shell: php artisan serve --host=0.0.0.0 --port=8000
      args:
        chdir: /var/www/lms
      async: 3600
      poll: 0
