---
- name: Install and deploy Laravel backend
  hosts: localhost
  become: yes
  vars:
    laravel_path: /var/www/lms/back

  tasks:
    - name: Install system dependencies
      apt:
        name:
          - git
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Clone the Laravel project
      git:
        repo: https://github.com/abdelrahim3AA/Learning-Management-Systems-LMS_GP.git
        dest: "{{ laravel_path }}"

    - name: Copy Dockerfile
      copy:
        src: Dockerfile
        dest: "{{ laravel_path }}/Dockerfile"
        mode: '0644'

    - name: Copy docker-compose.yml
      copy:
        src: docker-compose.yml
        dest: "{{ laravel_path }}/docker-compose.yml"
        mode: '0644'

    - name: Copy .env
      copy:
        src: "{{ laravel_path }}/.env.example"
        dest: "{{ laravel_path }}/.env"
        mode: '0644'

    - name: Copy entrypoint.sh
      copy:
        src: entrypoint.sh
        dest: "{{ laravel_path }}/entrypoint.sh"
        mode: '0755'

    - name: Copy nginx.conf
      copy:
        src: nginx.conf
        dest: "{{ laravel_path }}/nginx.conf"
        mode: '0644'

    - name: Build and run containers
      command: docker-compose up -d
      args:
        chdir: "{{ laravel_path }}"
