version: '3.8'
services:
  app:
    container_name: laravel_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/lms
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/lms
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
