apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: angular-nginx
  template:
    metadata:
      labels:
        app: angular-nginx
    spec:
      containers:
        - name: angular-nginx
          image: youssefkali/angular-nginx:latest
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: angular-nginx
spec:
  type: NodePort
  selector:
    app: angular-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
