---

- name: Install and deply Angular fronted
  hosts: localhost
  become: yes
  vars:
    frontDest: /var/www/lms/front
  vars_files:
    - dockerhub_credentials.yml
  tasks:
    - name: Pull Angular project
      git:
        repo: https://github.com/Mostafa27z/ai-lms.git
        dest: "{{ frontDest }}"

    - name: Install project dependincies
      command: npm install
      args:
        chdir: "{{ frontDest }}"

    - name: build the project
      shell: ng build --configuration production
      args:
        chdir: "{{ frontDest }}"
        executable: /bin/bash

    - name: Build the image
      command: docker build -t angular-nginx .
      args:
        chdir: "{{ frontDest }}"

    - name: Tag the image
      command: docker tag angular-nginx:latest youssefkali/angular-nginx:latest

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: Push image to Dockerhub
      command: docker push youssefkali/angular-nginx:latest

    - name: Restart the pods
      command: kubectl rollout restart deployment angular-nginx
      args:
        chdir: "{{ frontDest }}"
