apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: laravel
          image: youssefkali/laravel_app:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /var/www/lms/storage
              name: lms-volume
      volumes:
        - name: lms-volume
          persistentVolumeClaim:
            claimName: laravel-data
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  selector:
    app: laravel-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
