version: '3.8'

services:
  app:
    container_name: laravel_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - laravel_data:/var/www/lms

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - laravel_data:/var/www/lms
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
volumes:
  laravel_data:
