- name: Get certificate-authority-data
  shell: kubectl config view --raw -o jsonpath='{.clusters[0].cluster.certificate-authority-data}'
  register: cert_data

- name: Get Kubernetes API server IP
  shell: hostname -I | awk '{print $1}'
  register: kube_ip
