- name: Allow traffic from Jenkins container to k3s API server
  community.general.ufw:
    rule: allow
    from_ip: 172.17.0.2
    port: "6443"
    proto: tcp

- name: Allow SSH access through UFW
  community.general.ufw:
    rule: allow
    port: "22"
    proto: tcp

- name: Ensure UFW is enabled
  community.general.ufw:
    state: enabled
