- name: Clone LMS_DevOps repository for Docker setup
  git:
    repo: https://github.com/YoussefKhalidAli/LMS_DevOps.git
    dest: /tmp/LMS_DevOps
    version: main
    force: yes

- name: Creat /opt/laravel
  file:
    path: /opt/laravel
    state: directory
    mode: '0755'

- name: Copy Dockerfile from repository to current directory
  copy:
    src: /tmp/LMS_DevOps/AdvancedLaravelSetup/Dockerfile
    dest: /opt/laravel/Dockerfile
    remote_src: yes

- name: Copy nginx.conf from repository to current directory
  copy:
    src: /tmp/LMS_DevOps/AdvancedLaravelSetup/nginx.conf
    dest: /opt/laravel/nginx.conf
    remote_src: yes

- name: Copy docker-compose.yml from repository to current directory
  copy:
    src: /tmp/LMS_DevOps/AdvancedLaravelSetup/docker-compose
    dest: /opt/laravel/docker-compose.yml
