---
- name: Install and deploy Angular frontend
  hosts: localhost
  become: yes
  vars:
    angular_app_path: /var/www/lms/tst
    angular_build_output: /var/www/lms/tst/dist/ailms/browser

  tasks:
    - name: Install required system packages
      apt:
        name:
          - curl
          - git
          - nginx
        state: present
        update_cache: yes

    - name: Add Node.js 18.x repository
      ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      args:
        executable: /bin/bash

    - name: Install Node.js
      ansible.builtin.apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Install Angular CLI globally
      command: npm install -g @angular/cli

    - name: Clone the Angular project
      git:
        repo: https://github.com/Mostafa27z/ai-lms.git
        dest: "{{ angular_app_path }}"

    - name: Install project dependencies
      command: npm install
      args:
        chdir: "{{ angular_app_path }}"

    - name: Build the Angular project for production
      shell: ng build --configuration production
      args:
        chdir: "{{ angular_app_path }}"
        executable: /bin/bash

    - name: Set correct permissions for Angular dist folder
      file:
        path: "{{ angular_build_output }}"
        owner: www-data
        group: www-data
        mode: "0755"
        recurse: yes

    - name: Set up Nginx configuration for Angular
      template:
        src: nginx-angular.conf.j2
        dest: /etc/nginx/sites-available/angular-app
      notify:
        - Reload Nginx

    - name: Enable the Angular site in Nginx
      file:
        src: /etc/nginx/sites-available/angular-app
        dest: /etc/nginx/sites-enabled/angular-app
        state: link
        force: yes

    - name: Remove default Nginx site config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: restarted
        enabled: true

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
