- name: Set up K3s Cluster
  hosts: all
  become: yes
  roles:
    - role: k3s

- name: Deploy ai-lms project
  hosts: master
  vars:
    front_path: /var/www/lms/front
    back_path: /var/www/lms/back
  vars_files:
    - dockerCreds.yml
  become: yes
  roles:
    - role: common
    - role: git
    - role: deploy
