- name: Deploy ai-lms project
  hosts: localhost
  become: yes
  vars:
    front_path: /var/www/lms/front
    back_path: /var/www/lms/back
  vars_files:
    - dockerCreds.yml
  tasks:
    - name: Install system dependencies
      apt:
        name:
          - git
          - docker.io

    - name: Add Node.js 18.x repository
      ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      args:
        executable: /bin/bash

    - name: Install Node.js
      ansible.builtin.apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Install Angular CLI globally
      command: npm install -g @angular/cli

    - name: Instal k3s
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: clone front repo
      git:
        repo: https://github.com/Mostafa27z/ai-lms
        dest: "{{ front_path }}"

    - name: clone back repo
      git:
        repo: https://github.com/abdelrahim3AA/Learning-Management-Systems-LMS_GP
        dest: "{{ back_path }}"

    - name: Copy mysql files from localhost to target server
      copy:
        src: "{{ item }}"
        dest: "{{ back_path }}/k8sSetup/{{ item | basename }}"
      with_items:
        - ./backend/k3sSetup/mysql-secrets.yml
        - ./backend/k3sSetup/mysql-init-script.yml

    - name: deploy front
      command: kubectl apply -f deploy.yml
      args:
        chdir: "{{ front_path }}"

    - name: deploy back
      command: kubectl apply -f .
      args:
        chdir: "{{ back_path }}/k8sSetup"

    - name: Wait for at least one Laravel pod to be ready
      shell: |
        kubectl wait --for=condition=ready pod -l app=laravel --timeout=120s

    - name: Wait for at least mysql pod to be ready
      shell: |
        kubectl wait --for=condition=ready pod -l app=mysql --timeout=120s

    - name: Get the name of one Laravel pod
      shell: |
        kubectl get pods -l app=laravel -o jsonpath="{.items[0].metadata.name}"
      register: laravel_pod_name

    - name: Run Laravel migrations on just one pod
      shell: |
        kubectl exec {{ laravel_pod_name.stdout }} -- php artisan migrate --force

    - name: Start jenkins server
      command: >
        docker run --name jenkins -d -p 8080:8080 -p 50000:50000
        -v jenkins_data:/var/jenkins_home
        -v /var/run/docker.sock:/var/run/docker.sock
        jenkins/jenkins:lts

  post_tasks:
    - name: Show jenkins setup reminder
      debug:
        msg: "Playbook has finished running. Please remember to set up Jenkins"
