- name: Deploy ai-lms project
  hosts: server
  vars:
    front_path: /var/www/lms/front
    back_path: /var/www/lms/back
  vars_files:
    - dockerCreds.yml
  become: yes
  roles:
    - role: k3s
    - role: common
    - role: git
    - role: deploy
    - role: jenkins
