- name: Set the correct permissions for storage and cache directories
  command: docker exec -w /var/www/lms laravel_app chown -R www-data:www-data storage bootstrap/cache

- name: Set the correct permissions for database directory
  command: docker exec -w /var/www/lms laravel_app chown -R www-data:www-data database

- name: Set the correct permissions for the entire storage directory
  command: docker exec -w /var/www/lms laravel_app chmod -R 775 storage

- name: Set the correct permissions for the entire bootstrap/cache directory
  command: docker exec -w /var/www/lms laravel_app chmod -R 775 bootstrap/cache

- name: Create SQLite database file in the container
  command: docker exec -w /var/www/lms laravel_app touch /var/www/lms/database/database.sqlite

- name: Run Laravel migrations in the container
  command: docker exec -w /var/www/lms laravel_app php artisan migrate

- name: Clear Laravel routes in the container
  command: docker exec -w /var/www/lms laravel_app php artisan route:clear

- name: Clear Laravel config in the container
  command: docker exec -w /var/www/lms laravel_app php artisan config:clear

- name: Clear Laravel cache in the container
  command: docker exec -w /var/www/lms laravel_app php artisan cache:clear
